<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Gleb\Test1\Controller\Block $block */
?>
<div class="field">
    <div class="control">
        <label for="name">
            <span class="label">Name:</span>
            <input name="name" type="text" id="name" placeholder="Enter your name" data-validate="{required:true, 'validate-name':true}">
        </label>
    </div>
</div>
